import type { GetServerSideProps, GetServerSidePropsResult, NextPage } from 'next'
import Head from 'next/head'

const Profile: NextPage = () => {
  return (
    <Head>
      <title>Profile</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}

export const getServerSideProps: GetServerSideProps = async (): Promise<GetServerSidePropsResult<any>> => {
  return {
    props: {}
  }
}

export default Profile;
